Repository highVTest/E-Commerce-Front, pull requests merged in 2024-08, with the labels that each got.

#6 Feat/#4 implement main page
  package-lock.json
  package.json
  postcss.config.cjs
  src/App.css
  src/App.jsx
  src/global.css
  src/homepage/components/CommonLayout.jsx
  src/homepage/components/Header.jsx
  src/homepage/components/ProductDescription.jsx
  src/homepage/components/ProductDetail.jsx
  src/homepage/components/ProductList.jsx
  src/homepage/components/ProductReview.jsx
  src/homepage/components/SearchBar.jsx
  src/homepage/components/SearchResults.jsx
  src/homepage/components/SectionTitle.jsx
  src/homepage/pages/HomePage.jsx
  src/homepage/pages/PaymentPage.jsx
  src/homepage/pages/ProductDetailPage.jsx
  src/homepage/pages/SearchPage.jsx
  src/index.js
  vite.config.js
Labels: ✨Feat

#8 Seller backoffice
  package-lock.json
  package.json
  src/api/v1/product/product.js
  src/api/v1/seller-backoffice/sellerInfo.js
  src/main.jsx
  src/sellerbackoffice/SideNav.jsx
  src/sellerbackoffice/component/OrderList.jsx
  src/sellerbackoffice/component/Overview.jsx
  src/sellerbackoffice/component/ProductContainer.jsx
  src/sellerbackoffice/component/ProductForm.jsx
  src/sellerbackoffice/component/ProductList.jsx
  src/sellerbackoffice/component/SellerContainer.jsx
  src/sellerbackoffice/component/SellerInfoForm.jsx
  src/sellerbackoffice/component/css/OrderList.css
  src/sellerbackoffice/component/css/Overview.css
  src/sellerbackoffice/component/css/ProductForm.css
  src/sellerbackoffice/component/css/ProductList.css
  src/sellerbackoffice/component/css/SellerInfoForm.css
Labels: ✨Feat

#9 Feat/#5 implement image upload
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/api/upload.js
  src/api/v1/auth/oauth.js
  src/api/v1/client/auth.js
  src/api/v1/client/client.js
  src/api/v1/client/reviewClient.js
  src/api/v1/review/review.js
  src/constants.js
  src/index.css
  src/loginandreview/components/ReviewList.jsx
  src/loginandreview/components/login/KakaoLoginButton.jsx
  src/loginandreview/components/login/LoginForm.jsx
  src/loginandreview/components/login/RegisterForm.jsx
  src/loginandreview/components/review/ReviewForm.jsx
  src/loginandreview/pages/LoginLayout.jsx
  src/loginandreview/pages/LoginPage.jsx
  src/loginandreview/pages/RedirectPage.jsx
  src/loginandreview/pages/RegisterPage.jsx
  src/loginandreview/pages/ReviewPage.jsx
  src/loginandreview/pages/RootLayout.jsx
  src/loginandreview/pages/UploadPage.jsx
  src/main.jsx
  src/postcss.config.cjs
  src/router.jsx
Labels: ✨Feat

#17 Implement ProductPage, SellerInfoPage
  package-lock.json
  package.json
  src/api/v1/client.js
  src/api/v1/product/product.js
  src/api/v1/seller-backoffice/inventoryManagement.js
  src/api/v1/seller-backoffice/sellerInfo.js
  src/index.css
  src/router.jsx
  src/sellerbackoffice/component/ProductContainer.jsx
  src/sellerbackoffice/component/ProductCreateContainer.jsx
  src/sellerbackoffice/component/ProductCreateForm.jsx
  src/sellerbackoffice/component/ProductList.jsx
  src/sellerbackoffice/component/ProductListContainer.jsx
  src/sellerbackoffice/component/ProductUpdateContainer.jsx
  src/sellerbackoffice/component/ProductUpdateForm.jsx
  src/sellerbackoffice/component/SellerContainer.jsx
  src/sellerbackoffice/component/SellerInfoForm.jsx
  src/sellerbackoffice/component/css/SellerInfoForm.css
Labels: ✨Feat

#19 Feat/#11 implement mysql database connection
  src/homepage/components/ProductList.jsx
  src/router.jsx
Labels: ✨Feat

#15 Feat/#14 implement order page
  src/App.css
  src/App.jsx
  src/Components/TopBar.jsx
  src/api/v1/orders/orders.js
  src/buyer/components/BuyerCartForm.jsx
  src/buyer/components/LoginForm.jsx
  src/global.css
  src/index.css
  src/main.jsx
  src/payment/components/ExchangeModal.jsx
  src/payment/components/OrderDetailsModal.jsx
  src/payment/components/PaymentModal.jsx
  src/payment/components/RefundModal.jsx
  src/payment/css/BuyerOrderListPage.css
  src/payment/css/PaymentModal.css
  src/payment/pages/BuyerOrderListPage.jsx
  src/payment/pages/page.jsx
  src/router.jsx
Labels: ✨Feat

#22 Fix connect ProductImage
  src/homepage/components/SearchResults.jsx
Labels: 🐛Fix

#23 Feat/#18 impl review page
  .eslintrc.cjs
  package-lock.json
  package.json
  src/api/v1/auth/oauth.js
  src/api/v1/review/review.js
  src/loginandreview/components/ReviewList.jsx
  src/loginandreview/components/review/ReviewContainer.jsx
  src/loginandreview/components/review/ReviewInput.jsx
  src/loginandreview/pages/ReviewPage.jsx
  src/router.jsx
Labels: ✨Feat

#39 :recycle: refactor: Refactor button color gray
  src/Components/DaumPost.jsx
  src/Components/TopBar.jsx
  src/buyer/components/BuyerCartForm.jsx
  src/buyer/components/BuyerFavoriteForm.jsx
  src/buyer/components/BuyerInforForm.jsx
  src/buyer/components/BuyerProfileModal.jsx
  src/buyer/components/LoginForm.jsx
  src/buyer/components/css/BuyerCss.css
  src/buyer/pages/BuyerShopInfo.jsx
  src/buyer/pages/SellerLoginPage.jsx
  src/coupon/components/CreateCouponModal.jsx
  src/coupon/components/UpdateCouponModal.jsx
  src/coupon/pages/MyCouponPage.jsx
  src/homepage/components/ProductDetail.jsx
  src/homepage/components/ProductList.jsx
  src/homepage/components/SearchBarContainer.jsx
  src/homepage/components/SearchPageBar.jsx
  src/homepage/components/SearchProductsForm.jsx
  src/loginandreview/components/login/LoginForm.jsx
  src/loginandreview/components/login/RegisterForm.jsx
  src/loginandreview/components/login/SellerRegisterForm.jsx
  src/loginandreview/components/review/ReviewAddModal.jsx
  src/loginandreview/components/review/ReviewUpdateModal.jsx
  src/loginandreview/pages/LoginPage.jsx
  src/loginandreview/pages/MyReviewPage.jsx
  src/loginandreview/pages/RegisterPage.jsx
  src/loginandreview/pages/SellerRegisterPage.jsx
  src/payment/components/ExchangeModal.jsx
  src/payment/components/OrderDetailsModal.jsx
  src/payment/components/PaymentComponent.jsx
  src/payment/components/PaymentModal.jsx
  src/payment/components/RefundModal.jsx
  src/sellerbackoffice/Pages/OrderListPage.jsx
  src/sellerbackoffice/component/ProductCreateContainer.jsx
  src/sellerbackoffice/component/ProductCreateForm.jsx
  src/sellerbackoffice/component/ProductList.jsx
  src/sellerbackoffice/component/ProductUpdateForm.jsx
  src/sellerbackoffice/component/ProfileModal.jsx
  src/sellerbackoffice/component/SellerInfoForm.jsx
Labels: ♻Refactor

#41 ♻refactor: All
  public/images/Group70.png
  public/images/Login.jpg
  public/images/SellerLogin.jpg
  public/images/Untitled.jpg
  public/images/log-out.png
  public/images/login.png
  public/images/logo.png
  public/images/my-page.png
  public/images/seller-login.png
  public/images/seller-page.png
  public/images/slash.png
  src/App.css
  src/Components/TopBar.jsx
  src/api/v1/coupon/coupon.js
  src/api/v1/seller/seller.js
  src/buyer/components/BuyerFavoriteForm.jsx
  src/buyer/pages/BuyerShopInfo.jsx
  src/buyer/pages/ProductOnePage.jsx
  src/buyer/pages/SellerLoginPage.jsx
  src/coupon/components/CreateCouponModal.jsx
  src/coupon/components/UpdateCouponModal.jsx
  src/coupon/pages/CouponPage.jsx
  src/coupon/pages/MyCouponPage.jsx
  src/homepage/components/ProductContainer.jsx
  src/homepage/components/SearchPageBar.jsx
  src/homepage/components/SearchResults.jsx
  src/homepage/pages/ProductDetailPage.jsx
  src/index.css
  src/loginandreview/components/login/RegisterForm.jsx
  src/loginandreview/components/login/SellerRegisterForm.jsx
  src/loginandreview/components/review/ReviewContainer.jsx
  src/loginandreview/components/review/ReviewUpdateModal.jsx
  src/loginandreview/pages/LoginLayout.jsx
  src/loginandreview/pages/LoginPage.jsx
  src/loginandreview/pages/MyReviewPage.jsx
  src/loginandreview/pages/RedirectPage.jsx
  src/loginandreview/pages/UploadPage.jsx
  src/payment/components/ExchangeModal.jsx
  src/sellerbackoffice/Pages/OrderListPage.jsx
  src/sellerbackoffice/Pages/OrderStatusPage.jsx
  src/sellerbackoffice/Pages/StatisticsPages.jsx
  src/sellerbackoffice/SideNav.jsx
  src/sellerbackoffice/component/OrderList.jsx
  src/sellerbackoffice/component/ProductCreateContainer.jsx
  src/sellerbackoffice/component/ProductCreateForm.jsx
  src/sellerbackoffice/component/ProductList.jsx
  src/sellerbackoffice/component/ProductUpdateForm.jsx
  src/sellerbackoffice/component/SellerContainer.jsx
  src/sellerbackoffice/component/SellerInfoForm.jsx
  src/sellerbackoffice/component/SellerNavComponent.jsx
  src/sellerbackoffice/component/ShopCreateContainer.jsx
  src/sellerbackoffice/component/UpdateDeliveryModal.jsx
  src/sellerbackoffice/component/css/OrderList.css
  src/sellerbackoffice/component/css/ProductForm.css
  src/sellerbackoffice/component/css/ProductList.css
  src/sellerbackoffice/component/css/SellerInfoForm.css
Labels: ♻Refactor
